### ISSUE TITLE
[WIP] Virtual harassmap

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#14]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by lucie-docs** [comment]
@malteserteresa Are we still planning on implementing this?

**Comment by malteserteresa** [comment]
I'd love to but I think in the next 10000000 million years it will happen so lets close t for now

**Comment by lucie-docs** [comment]
Ok closing!
