### ISSUE TITLE
Use Matomo for analytics

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#19]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by lucie-docs** [comment]
Moved this to the Brand/Marketing Roadmap project as analytics is marketing-related.

**Comment by ribicn-softerrific** [comment]
Matomo was added by Teresa and it is merged to master and starting today we are using it on our site.

**Comment by lucie-docs** [comment]
Awesome, closing!
