### ISSUE TITLE
[WIP] Implement professional website design

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#21]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by lucie-docs** [comment]
Are there still things to do for this issue or is it done?

**Comment by ribicn-softerrific** [comment]
V0.3 of the website is done and online set before 8th of March. I suggest closing this issue and opening a new one when we start working on a new design.

**Comment by lucie-docs** [comment]
Ok, closing this issue!
