### ISSUE TITLE
Add Why we need to exist content to website content

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#22]
**Objective**
We want to show the people visiting the website why opt out tools exists

**Description**
We can use stats and quotes from our research to do this. This should just be a matter of choosing what to put.

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by malteserteresa** [comment]
These can then become copy for the crowdfunding campaign

**Comment by shepni** [comment]
Added to website content Google doc
