### ISSUE TITLE
[WIP] Create datastatement

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#24]
**Objective**
Create a datastatement that displays how our dataset was created

**Description**
Using inspiration from this paper https://transacl.org/ojs/index.php/tacl/article/view/1464 we want to create an infograph showing how our dataset was created.

**Skills**
Design

**Tools**

**Time Estimation**

**Tasks**

- [x] Use details from website content about self-collected dataset
- [x] Use details about Zeerak's dataset which can be found https://transacl.org/ojs/index.php/tacl/article/view/1464
- [x] Create datastatement

**Comment by lucie-docs** [comment]
Done, available here: https://docs.google.com/document/d/1qSqyDxbWrjNoKqYfWMxd8kXAva4iRMJj1TjD2blgUxI/edit?ts=5e219e2a#heading=h.hk6wmcnxdg2c
