### ISSUE TITLE
Disable second submission form and add success screen/light box

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#6]
**Objective**
Remove second survey on website

**Description**
The website currently has a submission form for the comments and a second submission for for further details that is optional. Until we get some GDPR guidance, we are to disable the second submission form

**Skills**
django

**Tools**

**Time Estimation**

**Tasks**

- [ ] Remove connection between submit and the screen "Would you like to give us more details?"
- [ ] Replace this will a submission confirmation lightbox/screen

**Comment by ribicn-softerrific** [comment]
@Morijarti Should i disable second form from opening in Angular also?

**Comment by lucie-docs** [comment]
Is this issue done?

**Comment by ribicn-softerrific** [comment]
Done. The second form is disabled.
